
version: "3.8"
services:
  database:
    image: mongo:4.2.2
    restart: always
#    ports:
 #     - "8080:27017"
    volumes:
      - ./data/db:/data/db
    env_file: .env
    environment:
        - AUTH=yes
        - MONGO_INIT_ROOT_USERNAME=rbladmin
        - MONGO_INIT_ROOT_PASSWORD=YouDontKnowMyPassw0rd

